---
title             : "Regression Tables"
shorttitle        : ""

author:
  - name          : "Daniel Yudkin"
    affiliation   : "1"


affiliation:
  - id            : "1"
    institution   : "University of Pennsylvania"


geometry          : margin=1.7cm

class             : "man"
header-includes   :

                    - \usepackage{siunitx}
                    - \sisetup {add-integer-zero=false}

output            : papaja::apa6_pdf

---

(ref:italp) _p_
(ref:ast) $^*$
(ref:beta) $\beta$
(ref:cross) $^\dagger$
(ref:cilower) $CI^{95\%}_{lower}$
(ref:ciupper) $CI^{95\%}_{upper}$

```{r setup, echo = F, include=F, results='asis', warning=FALSE}
knitr::opts_chunk$set(echo = F, include=TRUE, message=FALSE, tidy = TRUE, results='asis', warning=FALSE, tidy.opts=list(width.cutoff=60),tidy=TRUE)
```

```{r Load Sources}
library(here)
source(here::here('my-lm.R'))
```

```{r Set Outputs, eval= T,include=FALSE}
Console = F
PDF = T
```

```{r Set Controls, eval= T,include=FALSE}
mtcars.controls <- c("hp", "wt")
```

```{r Practice Regressions, eval = FALSE}
my.lm(mtcars, 
      dv = "mpg", 
      predictor = "cyl", 
      controls = mtcars.controls)

my.lm(mtcars, 
      dv = "mpg", 
      predictor = "carb", 
      controls = mtcars.controls)

my.lm(mtcars, 
      dv = "mpg", 
      predictor = "carb", 
      controls = mtcars.controls,
      add.controls = "cyl")

my.lm(mtcars, 
      dv = "mpg", 
      predictor = "carb", 
      controls = mtcars.controls,
      rm.controls = "hp")

my.lm(mtcars, 
      dv = "mpg", 
      predictor = "cyl", 
      controls = mtcars.controls) %>% 
        my.missing.data.model()
```


## Print Regression Table
```{r Regression Table}

PDF = T

my.lm(mtcars, 
      dv = "mpg", 
      predictor = "cyl", 
      controls = mtcars.controls,
      caption = "Example Regression Table")

```

