---
title             : "Regression Tables"
shorttitle        : ""

author:
  - name          : "Daniel Yudkin"
    affiliation   : "1"


affiliation:
  - id            : "1"
    institution   : "University of Pennsylvania"


geometry          : margin=1.7cm

class             : "man"
header-includes   :

                    - \usepackage{siunitx}
                    - \sisetup {add-integer-zero=false}

output            : papaja::apa6_pdf

---

(ref:italp) _p_
(ref:ast) $^*$
(ref:beta) $\beta$
(ref:cross) $^\dagger$
(ref:cilower) $CI^{95\%}_{lower}$
(ref:ciupper) $CI^{95\%}_{upper}$

```{r setup, echo = F, include=F, results='asis', warning=FALSE}
knitr::opts_chunk$set(echo = F, 
                      include=TRUE, 
                      message=FALSE, 
                      tidy = TRUE, 
                      results='asis', 
                      warning=FALSE, 
                      tidy.opts=list(width.cutoff=60),
                      tidy=TRUE)
```

```{r Load Sources}
library(here)
source(here::here('my-lmer.R'))

math_scores <- readRDS("example data.Rda")

```

```{r Set Outputs, eval= T,include=FALSE}
Console = T
PDF = F
```

```{r Set Controls, eval= T,include=FALSE}
math.controls <- c("sex", "ratio", "ses")

```

```{r Practice Regressions, eval = FALSE}
my.lmer(math_scores, 
      dv = "math", 
      predictor = "homework", 
      rdm.effect = "schid",
      controls = math.controls)

my.lmer(math_scores, 
      dv = "math", 
      predictor = "homework", 
      rdm.effect = "schid",
      controls = math.controls) %>% 
  my.missing.data.model()

```


## Print Regression Table
```{r Regression Table}

PDF = T
Console = F

my.lmer(math_scores, 
      dv = "math", 
      predictor = "homework", 
      rdm.effect = "schid",
      controls = math.controls,
      caption = "Multilevel Regression Table Example")

```

